default:
  app_name: "FastDemo"
  version: "0.1.0"
  logging:
    level: info
    file:
      path: "./logs"
  asr:
    provider: "faster-whisper"
    faster_whisper:
      model_size: "base"
      device: "cpu"
      compute_type: "int8"
development:
  reload: true
